sudo: required
services:
    - docker
before_install:
    - docker build -t kavitanethinti/docker-react -f Dockerfile.dev .

script:
    - docker run kavitanethinti/docker-react npm run test -- --coverage