sudo: required
services:
    - docker
before_install:
    - docker build -t kavitanethinti/docker-react -f Dockerfile.dev .

script:
    - docker run kavitanethinti/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-851647507899"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
